### ISSUE TITLE
Bug in my example

### ISSUE THREAD

**Issue by Zren** [koldbyte/termoid#1]
I could have sworn I updated it ages ago, guess not. Using ConfigPage might cause plasmashell to crash when you close the config window unless you use the following fix.

https://github.com/Zren/plasma-applets/blob/master/example/package/contents/ui/config/ConfigPage.qml

**Comment by koldbyte** [comment]
Thanks @Zren . I have updated the code as well as the release accordingly. 

This is my first KDE widget. Any code review/suggestions/pull requests are more than welcome. 

Also, I needed some help in fixing some issues like keyboard input not working on widget. Any pointers to solve this would be very helpful.
