### ISSUE TITLE
No output on version 2.0 or 2.1

### ISSUE THREAD

**Issue by kylemiller3** [koldbyte/termoid#11]
The console window just sits with no output at all on Ubuntu 18.04.
[https://i.imgur.com/vwDP77R.png](https://i.imgur.com/vwDP77R.png)

Commands tried:
echo 'Hello'
nethogs
/usr/bin/nethogs

**Comment by koldbyte** [comment]
@kylemiller3 
Please try the latest version v0.3 with keyboard support. https://store.kde.org/p/1169451/ 

Please also make sure you are using the older qmltermwidget - [0.1.0 release](https://github.com/Swordfish90/qmltermwidget/tree/v0.1.0) or [Commit 08958f7](https://github.com/Swordfish90/qmltermwidget/commit/08958f7c83a7d05627f623b8904f3e79a0b7366b) which is known to work.

You might need to restart plasmashell or reboot for the plasmoid to work.
`sudo killall plasmashell && kstart5 plasmashell`.

Still debugging on the crash issue with no solutions so far.

Let me know if it works for you.

**Comment by kylemiller3** [comment]
It is working properly now
