### ISSUE TITLE
Likely memory leak in v3

### ISSUE THREAD

**Issue by kylemiller3** [koldbyte/termoid#12]
Had two terminoids running and saw plasma shell eating memory until I had no more. Removed terminoids from my desktop and now there is no memory leak anymore.

**Comment by koldbyte** [comment]
@kylemiller3 I am not seeing much increase (~10mb only) on adding two termoids with htop and nethogs running as well.

How much memory is it taking in your case? 
Please post a screenshot of ksysguard with "All process - tree" mode enabled and plasmashell (and children processes) visible preferably both before and after adding termoid.

**Comment by kylemiller3** [comment]
[Mistaken and thought it was plasma shell but this is baseline](https://imgur.com/Pn4HzwT)
[After 8 minutes](https://i.imgur.com/Rz1mt12.png)
[After 12 minutes](https://i.imgur.com/wWTsJNb.png)
[After restarting sddm](https://i.imgur.com/sGtrx8G.png)
[After 3 minutes, no more leaking](https://i.imgur.com/2iD4rvh.png)

**Comment by koldbyte** [comment]
I see you have different applications running as well. Please try with a clean boot and no applications running. Just adding, interacting and removing termoids.
Xorg shared memory could be caused by something else as well.

**Comment by kylemiller3** [comment]
Well yeah as long as a desktop is running there are gonna be other applications running. The point is when running Terminoid it is causing something to leak - directly or indirectly - and the leak is fixed when its removed which is why I say it's likely the cause so the only variable in the test was Terminoid. I have tried to help but I don't really want to mess with this anymore because I can just use custom window settings for terminals on the desktop that definitely don't leak memory. Just letting you know.
