### ISSUE TITLE
Arguments are not accepted

### ISSUE THREAD

**Issue by t3kpunk** [koldbyte/termoid#2]
Hoi, I forked the code and added some code to accept the command line arguments. I use the widget for colortail -f /var/log/syslog

Also added opacity settings to the configuration menu .

Kind regards, widmar

**Comment by koldbyte** [comment]
Hi,
Please feel free to create a pull request when you feel the changes are stable. 
I will merge & update the store as well.
Thanks for contributing.

**Comment by koldbyte** [comment]
Hi,
I have merged your changes. It is working fine on my machine(Manjaro).
Please test the new version on your machine as well. 

Let me know if it is working good or you found some major issues. I will update the store as well after that.

Thanks.

**Comment by t3kpunk** [comment]
Thank you. I didn't see any irregularities also
