### ISSUE TITLE
Cannot assign to non-existent property "shellProgramArgs"

### ISSUE THREAD

**Issue by wincak** [koldbyte/termoid#5]
The plasmoid seems to fail to load on my machine:

`Error loading QML file: file:///home/wincak/.local/share/plasma/plasmoids/com.koldbyte.kde.termoid/contents/ui/main.qml:91:13: Cannot assign to non-existent property "shellProgramArgs"`

Version: 0.2.1 installed from store
OS: Manjaro
KDE Plasma: 5.11.4
KDE Frameworks: 5.40.0
Qt: 5.9.3
package qmltermwidget installed

Note: I wanted to uninstall and try version 0.2 but the "Download new Plasma widgets" dialog doesn't really allow me to uninstall anything (there is alway only the "Install" button - not just for this plasmoid). Also, where do you even find out which plasmoid version is installed?

**Comment by koldbyte** [comment]
This seems to be a version issue with qmltermwidget.

Which version are you using?

**Comment by wincak** [comment]
Version 0.1.0-2 - the current one from Manjaro community repo.

**Comment by koldbyte** [comment]
Please try the qmltermwidget-git from AUR. 

The version installed & working on my Manjaro system is 0.1.0.r27.g08958f7-1 for qmltermwidget-git.

I will update the documentation once you confirm its working with this latest package.

**Comment by wincak** [comment]
Good, it works now with the version you mentioned. Thanks!
However it would be better if it wasn't necessary to rely on AUR packages, especially those tracking unstable, development versions. At least later on.

**Comment by koldbyte** [comment]
Great. 
Its just that the latest version has not yet been released on https://github.com/Swordfish90/qmltermwidget

The last release was on Jan 2015 while this feature landed on Jul 2015 in the above repo.
The community repo only picks up when there is a release made.

**Comment by strangeattr** [comment]
I have tried qmltermwidget 0.1.0-2 (community, 06/12/2015 22:57:07), qmltermwidget-git 0.1.0.r2.g4d93f02-1 (aur) and a DIY package with the current git version cloned manually but nothing changes, I still get `Error loading QML file: file:///home/administrator/.local/share/plasma/plasmoids/com.koldbyte.kde.termoid/contents/ui/main.qml:91:13: Cannot assign to non-existent property "shellProgramArgs"`

**Comment by koldbyte** [comment]
It seems that the latest version of qmltermwidget is not being picked up. Everybody having issues solved this by installing the AUR or the git version.

I would advise to reboot OS after installing the AUR version of qmltermwidget-git (and removing other versions). If it still does not work, try uninstalling termoid and re-installing the latest version.

**Comment by CodingKoopa** [comment]
>I would advise to reboot OS

Might be worth noting that, for me, restarting the Plasma shell worked. I used `Alt`+`Space` to bring up KRunner, ran `killall plasmashell`, and then `plasmashell`.

**Comment by koldbyte** [comment]
This should be solved now for everyone.

Please try the latest version v0.3 with keyboard support. https://store.kde.org/p/1169451/ 

Please also make sure you are using the older qmltermwidget - [0.1.0 release](https://github.com/Swordfish90/qmltermwidget/tree/v0.1.0) or [Commit 08958f7](https://github.com/Swordfish90/qmltermwidget/commit/08958f7c83a7d05627f623b8904f3e79a0b7366b) which is known to work.

You might need to restart plasmashell or reboot for the plasmoid to work.
`sudo killall plasmashell && kstart5 plasmashell`.

Still debugging on the crash issue with no solutions so far.

Let me know if it works for you.
