### ISSUE TITLE
Widget is way too small

### ISSUE THREAD

**Issue by RealBloodman** [koldbyte/termoid#9]
On my laptop I'm currently on KDE Neon (Upgraded to 18.04) and for some reason the widget is just wayyy too small and I have followed all the instructions properly. In the attachment you can see how small it looks and it won't change no matter the font size. Hope there's a fix for this..
![picture](https://user-images.githubusercontent.com/36970693/43314312-3c417172-919b-11e8-80eb-825e4a226558.png)

**Comment by koldbyte** [comment]
Its not related to the font size. 
You can try the usual way to resize the plasmoid.

https://askubuntu.com/questions/761138/how-to-move-resize-or-remove-kde-widgets-since-plasma-5-5-5-xenial
